### ISSUE TITLE
Filter search short circuiting

### ISSUE THREAD

**Issue by hohMiyazawa** [veluca93/fpnge#16]
In some images (mainly photographic content), considering other filters than paeth is futile.

I therefore tested a simple heuristic: Group scanlines into groups of 8. If the filter search selects paeth for all of the first 3, the remaining five get paeth applied as well without other filters considered.

This reaps most of the benefits of optimal filter selection, at the cost of half of ``fpnge4``'s speed advantage over ``fpnge``.

Sorted file sizes for a corpus of images, both photographic and synthetic images:

![heuristics_2](https://user-images.githubusercontent.com/58218853/180107992-22ed5a58-4e6b-4b9e-9c32-cb92ac354e8e.png)

While this is just a quick attempt, I think it shows that trying to achieve near optimal filter selection without doing a full filter search is both doable and worthwhile.

The opposite case, getting rid of paeth calculations in images where paeth doesn't perform well may also yield some gains. (flat areas?)

**Comment by animetosho** [comment]
Interesting suggestion! Yeah, there does seem to be scope to speed up filter selection with heuristics, such as your idea, or perhaps not sampling whole rows etc.

I had also played around with using more traditional sum-of-absolute-difference style testing, which gives a speed boost over the current 'mock encode' system. It also allows the symbol collection (for Huffman) to not be [stuck with only Paeth filtering](https://github.com/veluca93/fpnge/blob/be4c66a5666f10d33a6da21f8ce2da39290fcdb3/fpnge.cc#L1220) (so might be more accurate).  
Could also be combined with your idea as well.

**Comment by hohMiyazawa** [comment]
Another simple heuristic tested: In each group of scanlines (32?), stop testing a filter if it hasn't been selected yet after some fraction of the scanlines have been searched (half?)

Speed gains on synthetic images as well, with similar density losses to the previous heuristics.
Density losses do not stack much when both are used.

**Comment by hohMiyazawa** [comment]
One benefit of the mock encode approach is that it generates actual costs. That's in theory better data for a proper heuristic than just information about what filter was previously selected.

**Comment by veluca93** [comment]
Would either of you feel like sending a PR with one of the approaches above? :)

**Comment by hohMiyazawa** [comment]
Can do, code is more precise than words.

This only requires modifications in the ``EncodeOneRow`` function, passing it the current line number and some kind of statistic object as additional arguments.

**Comment by animetosho** [comment]
> Would either of you feel like sending a PR with one of the approaches above? :)

I don't have any test suite to evaluate the overall effectiveness, so haven't bothered to go any further.  
But essentially `PredictVec` gets changed into `GetPredictor` (i.e. it doesn't subtract from the data), and the `TryPredictor` calls get replaced with the following:

~~~
static uint8_t BestSADPredictor(size_t bytes_per_line,
                                const unsigned char *current_row_buf,
                                const unsigned char *top_buf,
                                const unsigned char *left_buf,
                                const unsigned char *topleft_buf) {

  size_t i = 0;
  auto cost1 = MMSI(setzero)();
  auto cost2 = MMSI(setzero)();
  auto cost3 = MMSI(setzero)();
  auto cost4 = MMSI(setzero)();
  for (; i + SIMD_WIDTH <= bytes_per_line; i += SIMD_WIDTH) {
    auto data = MMSI(load)((MIVEC *)(current_row_buf + i));
    auto pred1 = GetPredictor<1>(top_buf + i, left_buf + i);
    auto pred2 = GetPredictor<2>(top_buf + i, left_buf + i);
    auto pred3 = GetPredictor<3>(top_buf + i, left_buf + i);
    auto pred4 = GetPredictor<4>(top_buf + i, left_buf + i, topleft_buf + i);
    cost1 = MM(add_epi64)(cost1, MM(sad_epu8)(data, pred1));
    cost2 = MM(add_epi64)(cost2, MM(sad_epu8)(data, pred2));
    cost3 = MM(add_epi64)(cost3, MM(sad_epu8)(data, pred3));
    cost4 = MM(add_epi64)(cost4, MM(sad_epu8)(data, pred4));
  }
  // worth considering: the last vector can probably be skipped for being not so
  // relevant, but probably needed for images < 32px wide
  size_t bytes_remaining =
      bytes_per_line ^ i; // equivalent to `bytes_per_line - i`
  if (bytes_remaining) {
    auto data = MMSI(load)((MIVEC *)(current_row_buf + i));
    auto pred1 = GetPredictor<1>(top_buf + i, left_buf + i);
    auto pred2 = GetPredictor<2>(top_buf + i, left_buf + i);
    auto pred3 = GetPredictor<3>(top_buf + i, left_buf + i);
    auto pred4 = GetPredictor<4>(top_buf + i, left_buf + i, topleft_buf + i);

    auto maskv = MMSI(loadu)((MIVEC *)(kMaskVec - bytes_remaining));
    // data and pred2 doesn't need to be masked, because the buffer is
    // zero-filled
    pred1 = MMSI(and)(pred1, maskv);
    pred3 = MMSI(and)(pred3, maskv);
    pred4 = MMSI(and)(pred4, maskv);

    cost1 = MM(add_epi64)(cost1, MM(sad_epu8)(data, pred1));
    cost2 = MM(add_epi64)(cost2, MM(sad_epu8)(data, pred2));
    cost3 = MM(add_epi64)(cost3, MM(sad_epu8)(data, pred3));
    cost4 = MM(add_epi64)(cost4, MM(sad_epu8)(data, pred4));
  }

  uint8_t predictor = 1;
  size_t best_cost = hadd(cost1);
  auto test_cost = [&](MIVEC costv, uint8_t pred) {
    size_t cost = hadd(costv);
    if (cost < best_cost) {
      best_cost = cost;
      predictor = pred;
    }
  };
  test_cost(cost2, 2);
  test_cost(cost3, 3);
  test_cost(cost4, 4);
  return predictor;
}
~~~

(I wrote this before I realised that the Paeth prediction can be reused for a speed boost, but that could be added above without too much hassle)  
You could also then change the `ProcessRow` call in collect symbols to test for the appropriate predictor, though that might clash a bit with @hohMiyazawa's heuristic.

Actually, this does clash with @hohMiyazawa's idea of skipping some filter tests, since I always do all four. I suppose you could try to incorporate it to some extent, but the key benefit of the above is merging four passes into one, where trying out predictor 1 and 2 is almost free.

Whilst this does improve performance over the current code (one pass instead of four, skips RLE and trying to look up symbol costs), I was mainly looking at this if more sophisticated LZ77 is introduced. The current mock encode system would require LZ77 be applied five times (like how RLE currently is), which would presumably be rather slow, but a SAD heuristic allows that to be bypassed.

**Comment by hohMiyazawa** [comment]
I think that for an optimizing encoder, one can't completely avoid doing full filter searches.

The fundamental reason would be that the residuals will have different LZ characteristics, so match finding (or RLE) has to be redone for every filter.
If i remember correctly, that was one of the reasons LZ is done on pixels instead of bytes in WebP.

So for synthetic-type images, were LZ/RLE matters, some density loss is unavoidable if one tries to bypass a full filter search in any way. But for photographic content, the optimal strategy is almost always just full paeth prediction + some fast RLE attempt.

**Comment by hohMiyazawa** [comment]
@[animetosho](https://github.com/animetosho) I would very much be interested to see a completed version of that.
Then I can throw the current heuristic attempt into the trash, and try to find some that work well (it at all?) on top of your better filter search.

**Comment by animetosho** [comment]
Not sure whether you'd consider fpnge to be an 'optimizing encoder', but *most* PNG encoders don't include LZ77 in the filter search. Usually filtering and deflate are considered completely separate, with the latter relying on data from the former, so doing mock encodes isn't even possible with most PNG encoder designs.  
As such, they need a heuristic for filter selection, and SAD happens to be the most commonly used (see libpng as an example).

Of course fpnge has different constraints, and since it builds the Huffman tree up front, it has the ability to do mock encodes for better accuracy at the expense of speed.  
fpnge currently doesn't do any LZ77 except for detecting reasonably long sequences of 0 and encoding it as a run. Conveniently, 0 is also considered 'no cost' when doing a SAD, so the heuristic lines up.

I don't consider my suggestion to be a 'better' filter search. I was just throwing out an idea I had been exploring, since there was interest in faster prediction trials at the expense of density.  
Maybe I'll get around to doing a full implementation; I'm hesitant for it to be integrated as is, as I generally think fpnge is fast enough already to need further compromises on compression. It would make more sense if there was some 'speed' option perhaps (or do what the fixed predictors currently do and guard it behind an ifdef).

**Comment by animetosho** [comment]
Alright, [here's](https://github.com/animetosho/fpnge/commit/2d15e35ad29e315789add8e85b39416112aeab90) a full implementation of the idea. Remember to compile with `FPNGE_SAD_PREDICTOR` to enable.

**Comment by animetosho** [comment]
Combining the various strategies, and testing with [these images](https://storage.animetosho.org/ul/png-testset.zip), I got this result:

![size comparison](https://user-images.githubusercontent.com/12937885/181184112-500b892f-5c96-430b-b3b9-84c191d58999.png)

**Comment by veluca93** [comment]
Closing this since https://github.com/veluca93/fpnge/pull/19 is in, opened #20 for future improvements.
